
import { Button, Col, Container, OverlayTrigger, Row, Tooltip } from 'react-bootstrap';
import Head from 'next/head'

import styles from './index.module.css';
import Logo from '../../components/logo/logo';

import UserInformation from "../../components/userinformation/userinformation.js";
function About({ }) {
    return (
        <>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 style={{textAlign: 'center'}}> Acerca de mi</h1>
            <br />
            <UserInformation />
            <br />
            <br />
            <br />
            <br />
            <Container className={styles.logo_container}>
                <Logo height="88" width="300" />
            </Container>
            <br />
        </>
    );
}

export default About;