import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useState } from 'react';
import { Button, Col, Container, OverlayTrigger, Row, Tooltip } from 'react-bootstrap';
import Logo from "../components/logo/logo.js";
import Avatar from '../components/avatar/avatar';
import UserInformation from "../components/userinformation/userinformation.js";

const renderTooltip = (props) => (
  <Tooltip id="button-tooltip" {...props}>
    Nao pode poseer menos da 0 pepas
  </Tooltip>
);


const Overlay = ({ ButtonComponent }) => {
  return (

    <OverlayTrigger
      placement="top"
      delay={{ show: 0, hide: 0 }}
      overlay={renderTooltip}
    >
      <Button variant="warning">
        Menos

      </Button>
    </OverlayTrigger>
  )
    ;
}

const Example = ({ }) => {
  const [pepas, setPepas] = useState(0);
  return (
    <Container className={styles.example_container}>
      <h2>
        Actualmente hay
        {
          pepas == 1 ?
            (` ${pepas} pepa`)
            :
            (` ${pepas} pepas`)
        }
      </h2>
      <h4>
        Segun los terminos y las condiciones dadas en el transcurso de la navegacion, ¿Desea mas pepas?
      </h4>
      <Row>
        <Button onClick={() => setPepas((element) => element + 1)} variant="danger">
          Mas
        </Button>
      </Row>
      <br />
      <Row>
        {
          pepas == 0 &&
          <Overlay />
        }
        {
          pepas > 0 &&
          <Button onClick={() => setPepas((element) => element - 1)} className={`height: 100px`} variant="warning">
            Menos
          </Button>
        }
      </Row>
    </Container>
  )
}


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>
        Benvenuti manito
      </h1>
      <br />

      <UserInformation />

      <br />
      <br />
      <Example />

      <br />
      <br />
      <Container className={styles.logo_container}>
        <Logo height="88" width="300" />
      </Container>
      <br />
      {
        /*
    
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
    
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
    
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
    
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
    
          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>
    
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
    
            */
      }
    </div >
  )
}
