import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useState } from 'react';
import { Button, Row } from 'react-bootstrap';

export default function Home() {
  const [pepas, setPepas] = useState(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>
        Benvenuti manito
      </h1>

      <h2>
        Actualmente hay 
        {
          pepas == 1 ?
          (` ${pepas} pepa`)
          :
          (` ${pepas} pepas`)
        }
      </h2>
      <h3>
        Queres mas pepas?
      </h3>
      <Row>
        <Button onClick={() => setPepas((element) => element + 1)} variant="danger">
          Mas
        </Button>

      </Row>
      <br />
      <Row>
        {
          pepas == 0 &&
          <Button disabled variant="warning">
            Menos
          </Button>
        }
        {
          pepas > 0 &&
          <Button onClick={() => setPepas((element) => element - 1)} className={`height: 100px`} variant="warning">
            Menos
          </Button>
        }
      </Row>
      {
        /*

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

            */
      }
    </div>
  )
}
